[[block]]
block = "net"
ssid = true
ip = true
device = "enp5s0f1"
speed_up = false
speed_down = false

[[block]]
block = "net"
ssid = true
ip = true
device = "enp0s31f6"
speed_up = true 
speed_down = true 

[[block]]
block = "music"
player = "mpd"
buttons = ["play", "next"]

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "uptime"

[[block]]
block = "nvidia_gpu"
label = "GTX 1060"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "time"
interval = 1
format = "%a %d/%b/%Y %H:%M:%S"

[theme]
name = "slick"

[icons]
name = "awesome"
