theme = "slick"
icons = "awesome"


[[block]]
block = "net"
ip = true
device = "enp57s0u1u2"
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true

[[block]]
block = "net"
ssid = true
ip = true
device = "wlp58s0"
speed_up = false
speed_down = false

[[block]]
block = "music"
player = "mpd"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% ({time})"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 1
format = "%a %d/%b/%Y %H:%M:%S"
